// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use diesel::{Queryable, Identifiable};
use serde::{Serialize,Deserialize};

use chrono::NaiveDateTime;
#[derive(Serialize,Deserialize,Queryable)]
#[diesel(table_name = User)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub name: String,
    pub password: String,
    pub created_at: NaiveDateTime,
}

