apiVersion: v1
kind: Pod
metadata:
  name: b2brp-backend
  namespace: b2brp
  labels:
    name: b2brp-backend
    app: b2brp-backend
spec:
  containers:
    - name: b2brp-backend
      image: ghcr.io/mucks/b2brp-backend:main
      imagePullPolicy: Always
      ports:
        - containerPort: 4000
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: b2brp-backend-secret
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: b2brp-backend-secret
              key: JWT_SECRET
        - name: RUST_LOG
          value: "debug"
