[features]
seeds = false
skip-lint = false
[programs.localnet]
b2brp_solana_contract = "3EMMqhy7w8PYobaxMfxhH6CMjxPgpVmdCZZSq2Pt2oys"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mucks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
